# This file was generated by GoReleaser. DO NOT EDIT.
cask "watch-docker" do
  name "watch-docker"
  desc "Watch Docker - Docker Container Management and Monitoring Tool"
  homepage "https://github.com/jianxcao/watch-docker"
  version "0.1.14"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "watch-docker"

  on_macos do
    on_intel do
      url "https://github.com/jianxcao/watch-docker/releases/download/v#{version}/watch-docker_#{version}_darwin_x86_64.tar.gz"
      sha256 "7ea709457d386fd782c0985ef1a9cdd6051f1ed233e0a1f28dc5e009f6c02640"
    end
    on_arm do
      url "https://github.com/jianxcao/watch-docker/releases/download/v#{version}/watch-docker_#{version}_darwin_arm64.tar.gz"
      sha256 "bf89d648f1d2b296a800d3c045b7f36d16c3a5201b51cbdcf33dde1c78eb86ba"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jianxcao/watch-docker/releases/download/v#{version}/watch-docker_#{version}_linux_x86_64.tar.gz"
      sha256 "dbaf51393d461ff5db8a32cb3a976de8156b18d111e77727fe1472dbd48f1d51"
    end
    on_arm do
      url "https://github.com/jianxcao/watch-docker/releases/download/v#{version}/watch-docker_#{version}_linux_arm64.tar.gz"
      sha256 "c0f91464b36597ed5dcf4e48d0ad1f0e42514ff4d30a461fc1b3b1bb0b16e0e5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/watch-docker"]
    end
    # 创建配置目录
    (Pathname.new(ENV['HOME'])/".watch-docker").mkpath
  end

  caveats do
    "📦 安装完成！配置目录：~/.watch-docker"
    ""
    "🚀 设置开机自启动："
    ""
    "1. 查找 watch-docker 安装路径："
    "   which watch-docker"
    ""
    "2. 复制提供的 launchd 配置文件："
    "   cp "$(brew --prefix)/Caskroom/watch-docker/*/com.watchdocker.plist" ~/Library/LaunchAgents/"
    ""
    "3. 编辑配置文件，确认二进制路径正确："
    "   # 对于 Apple Silicon (M1/M2/M3):"
    "   /opt/homebrew/bin/watch-docker"
    "   # 对于 Intel Mac:"
    "   /usr/local/bin/watch-docker"
    ""
    "4. 加载并启动服务："
    "   launchctl load ~/Library/LaunchAgents/com.watchdocker.plist"
    "   launchctl start com.watchdocker"
    ""
    "📝 服务管理命令："
    "   启动: launchctl start com.watchdocker"
    "   停止: launchctl stop com.watchdocker"
    "   重启: launchctl kickstart -k gui/$(id -u)/com.watchdocker"
    "   查看状态: launchctl list | grep watchdocker"
    "   卸载自启: launchctl unload ~/Library/LaunchAgents/com.watchdocker.plist"
    ""
    "📖 查看日志："
    "   tail -f ~/.watch-docker/stdout.log"
    "   tail -f ~/.watch-docker/stderr.log"
    ""
    "⚙️ 默认访问：http://localhost:8080"
    "   默认用户名/密码：admin/admin"
  end

  # No zap stanza required
end
